/**
 * One-time payment links are generated by a separate VeriPay service, not here.
 * This is the seam: the application depends on the interface, and swapping the
 * stub for the real client touches only this file.
 */

export interface LinkRequest {
  agreementId: string;
  listingId: string;
  conversationId: string;
  agreedPrice: number;
  buyerId: string;
  sellerId: string;
}

export interface IssuedLink {
  url: string | null;
  expiresAt: string | null;
  status: string;
}

export interface LinkProvider {
  issue(req: LinkRequest): Promise<IssuedLink>;
}

/**
 * Ships today. Emits a link event with no URL so the UI can render the
 * "link coming soon" state without inventing a dead URL.
 */
export class StubLinkProvider implements LinkProvider {
  async issue(_req: LinkRequest): Promise<IssuedLink> {
    return { url: null, expiresAt: null, status: "pending_link_service" };
  }
}

/**
 * The shape the real implementation will take, for whoever builds the link
 * service. Deliberately not wired up yet.
 *
 *   POST ${VERIPAY_LINK_SERVICE_URL}/links
 *   Authorization: Bearer <machine-to-machine token>
 *   Idempotency-Key: <agreementId>
 *   { agreementId, listingId, conversationId, agreedPrice, buyerId, sellerId }
 *   -> 200 { url, expiresAt, status }
 *
 * `agreementId` is stable per (conversationId, listingId), so retries are safe:
 * the link service must return the same link for a repeated agreementId rather
 * than minting a second one-time link.
 */

let provider: LinkProvider = new StubLinkProvider();

export const getLinkProvider = (): LinkProvider => provider;
export const setLinkProvider = (next: LinkProvider): void => {
  provider = next;
};
